/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedPanelRouteRouteImport } from './routes/_authenticated/panel/route'
import { Route as AuthenticatedPanelIndexRouteImport } from './routes/_authenticated/panel/index'
import { Route as AuthenticatedPanelBuzonRouteImport } from './routes/_authenticated/panel/buzon'
import { Route as AuthenticatedPanelChatRouteImport } from './routes/_authenticated/panel/chat'
import { Route as AuthenticatedPanelEditorRouteImport } from './routes/_authenticated/panel/editor'
import { Route as AuthenticatedPanelNotasRouteImport } from './routes/_authenticated/panel/notas'
import { Route as AuthenticatedPanelPortafolioRouteImport } from './routes/_authenticated/panel/portafolio'
import { Route as AuthenticatedPanelVersionesRouteImport } from './routes/_authenticated/panel/versiones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelRouteRoute = AuthenticatedPanelRouteRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelIndexRoute = AuthenticatedPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPanelRouteRoute,
} as any)
const AuthenticatedPanelBuzonRoute = AuthenticatedPanelBuzonRouteImport.update({
  id: '/buzon',
  path: '/buzon',
  getParentRoute: () => AuthenticatedPanelRouteRoute,
} as any)
const AuthenticatedPanelChatRoute = AuthenticatedPanelChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedPanelRouteRoute,
} as any)
const AuthenticatedPanelEditorRoute =
  AuthenticatedPanelEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AuthenticatedPanelRouteRoute,
  } as any)
const AuthenticatedPanelNotasRoute = AuthenticatedPanelNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedPanelRouteRoute,
} as any)
const AuthenticatedPanelPortafolioRoute =
  AuthenticatedPanelPortafolioRouteImport.update({
    id: '/portafolio',
    path: '/portafolio',
    getParentRoute: () => AuthenticatedPanelRouteRoute,
  } as any)
const AuthenticatedPanelVersionesRoute =
  AuthenticatedPanelVersionesRouteImport.update({
    id: '/versiones',
    path: '/versiones',
    getParentRoute: () => AuthenticatedPanelRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/panel': typeof AuthenticatedPanelRouteRouteWithChildren
  '/panel/buzon': typeof AuthenticatedPanelBuzonRoute
  '/panel/chat': typeof AuthenticatedPanelChatRoute
  '/panel/editor': typeof AuthenticatedPanelEditorRoute
  '/panel/notas': typeof AuthenticatedPanelNotasRoute
  '/panel/portafolio': typeof AuthenticatedPanelPortafolioRoute
  '/panel/versiones': typeof AuthenticatedPanelVersionesRoute
  '/panel/': typeof AuthenticatedPanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/panel/buzon': typeof AuthenticatedPanelBuzonRoute
  '/panel/chat': typeof AuthenticatedPanelChatRoute
  '/panel/editor': typeof AuthenticatedPanelEditorRoute
  '/panel/notas': typeof AuthenticatedPanelNotasRoute
  '/panel/portafolio': typeof AuthenticatedPanelPortafolioRoute
  '/panel/versiones': typeof AuthenticatedPanelVersionesRoute
  '/panel': typeof AuthenticatedPanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRouteRouteWithChildren
  '/_authenticated/panel/buzon': typeof AuthenticatedPanelBuzonRoute
  '/_authenticated/panel/chat': typeof AuthenticatedPanelChatRoute
  '/_authenticated/panel/editor': typeof AuthenticatedPanelEditorRoute
  '/_authenticated/panel/notas': typeof AuthenticatedPanelNotasRoute
  '/_authenticated/panel/portafolio': typeof AuthenticatedPanelPortafolioRoute
  '/_authenticated/panel/versiones': typeof AuthenticatedPanelVersionesRoute
  '/_authenticated/panel/': typeof AuthenticatedPanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/panel'
    | '/panel/buzon'
    | '/panel/chat'
    | '/panel/editor'
    | '/panel/notas'
    | '/panel/portafolio'
    | '/panel/versiones'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/panel/buzon'
    | '/panel/chat'
    | '/panel/editor'
    | '/panel/notas'
    | '/panel/portafolio'
    | '/panel/versiones'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/panel'
    | '/_authenticated/panel/buzon'
    | '/_authenticated/panel/chat'
    | '/_authenticated/panel/editor'
    | '/_authenticated/panel/notas'
    | '/_authenticated/panel/portafolio'
    | '/_authenticated/panel/versiones'
    | '/_authenticated/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel/': {
      id: '/_authenticated/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof AuthenticatedPanelIndexRouteImport
      parentRoute: typeof AuthenticatedPanelRouteRoute
    }
    '/_authenticated/panel/buzon': {
      id: '/_authenticated/panel/buzon'
      path: '/buzon'
      fullPath: '/panel/buzon'
      preLoaderRoute: typeof AuthenticatedPanelBuzonRouteImport
      parentRoute: typeof AuthenticatedPanelRouteRoute
    }
    '/_authenticated/panel/chat': {
      id: '/_authenticated/panel/chat'
      path: '/chat'
      fullPath: '/panel/chat'
      preLoaderRoute: typeof AuthenticatedPanelChatRouteImport
      parentRoute: typeof AuthenticatedPanelRouteRoute
    }
    '/_authenticated/panel/editor': {
      id: '/_authenticated/panel/editor'
      path: '/editor'
      fullPath: '/panel/editor'
      preLoaderRoute: typeof AuthenticatedPanelEditorRouteImport
      parentRoute: typeof AuthenticatedPanelRouteRoute
    }
    '/_authenticated/panel/notas': {
      id: '/_authenticated/panel/notas'
      path: '/notas'
      fullPath: '/panel/notas'
      preLoaderRoute: typeof AuthenticatedPanelNotasRouteImport
      parentRoute: typeof AuthenticatedPanelRouteRoute
    }
    '/_authenticated/panel/portafolio': {
      id: '/_authenticated/panel/portafolio'
      path: '/portafolio'
      fullPath: '/panel/portafolio'
      preLoaderRoute: typeof AuthenticatedPanelPortafolioRouteImport
      parentRoute: typeof AuthenticatedPanelRouteRoute
    }
    '/_authenticated/panel/versiones': {
      id: '/_authenticated/panel/versiones'
      path: '/versiones'
      fullPath: '/panel/versiones'
      preLoaderRoute: typeof AuthenticatedPanelVersionesRouteImport
      parentRoute: typeof AuthenticatedPanelRouteRoute
    }
  }
}

interface AuthenticatedPanelRouteRouteChildren {
  AuthenticatedPanelBuzonRoute: typeof AuthenticatedPanelBuzonRoute
  AuthenticatedPanelChatRoute: typeof AuthenticatedPanelChatRoute
  AuthenticatedPanelEditorRoute: typeof AuthenticatedPanelEditorRoute
  AuthenticatedPanelNotasRoute: typeof AuthenticatedPanelNotasRoute
  AuthenticatedPanelPortafolioRoute: typeof AuthenticatedPanelPortafolioRoute
  AuthenticatedPanelVersionesRoute: typeof AuthenticatedPanelVersionesRoute
  AuthenticatedPanelIndexRoute: typeof AuthenticatedPanelIndexRoute
}

const AuthenticatedPanelRouteRouteChildren: AuthenticatedPanelRouteRouteChildren =
  {
    AuthenticatedPanelBuzonRoute: AuthenticatedPanelBuzonRoute,
    AuthenticatedPanelChatRoute: AuthenticatedPanelChatRoute,
    AuthenticatedPanelEditorRoute: AuthenticatedPanelEditorRoute,
    AuthenticatedPanelNotasRoute: AuthenticatedPanelNotasRoute,
    AuthenticatedPanelPortafolioRoute: AuthenticatedPanelPortafolioRoute,
    AuthenticatedPanelVersionesRoute: AuthenticatedPanelVersionesRoute,
    AuthenticatedPanelIndexRoute: AuthenticatedPanelIndexRoute,
  }

const AuthenticatedPanelRouteRouteWithChildren =
  AuthenticatedPanelRouteRoute._addFileChildren(
    AuthenticatedPanelRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPanelRouteRoute: typeof AuthenticatedPanelRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPanelRouteRoute: AuthenticatedPanelRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
